---
- name: Configure NE Intermediary
  hosts: eqx

  tasks:
  - name: convert config json to dict
    ansible.builtin.set_fact:
      config: "{{ config_json | from_json }}"
  - name: Configure customer side interfaces
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "{{ item.name }}"
        ipv4:
        - address: "{{ item.ip }}"
      - name: "GigabitEthernet9"
        ipv4:
        - address: "{{ config.wan_ip }}"
    loop: "{{ config.interfaces }}"
  - name: turn up interfaces
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ item.name }}"
        enabled: true
      - name: "GigabitEthernet9"
        enabled: true
    loop: "{{ config.interfaces }}"
  - name: Configure BGP globals
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{ config.customer_side_asn }}"
        bgp:
          router_id: 
            address: "{{ config.router_id }}"
          log_neighbor_changes: true
        networks:
        - address: "{{ config.wan_network }}"
          netmask: "{{ config.wan_netmask }}"
        neighbors:
        - neighbor_address: "{{ item.ip }}"
          activate: true
          remote_as: "{{ item.asn }}"
          password_options:
            encryption: 0
            pass_key: "{{ item.auth_key }}"
    loop: "{{ config.neighbors }}"
  - name: Save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified