---
- name: Configure NE Intermediary
  hosts: eqx

  tasks:
  - name: convert config json to dict
    ansible.builtin.set_fact:
      config: "{{ config_json | from_json }}"
  - name: Configure customer side interfaces
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "{{ item.name }}"
        ipv4:
        - address: "{{ item.ip }}"
      - name: "GigabitEthernet9"
        ipv4:
        - address: "{{ config.wan_ip }}"
      loop: "{{ config.interfaces }}"
  - name: Configure BGP
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{ config.customer_side_asn }}"
        router_id: 
        - address: "{{ config.router_id }}"
        log_neighbor_changes:
          set: true
        neighbors:
        - neighbor_address: "{{ item.ip }}"
          activate: true
          remote_as: "{{ item.asn }}"
        networks:
        - address: "{{ config.wan_network }}"
      loop: "{{ config.neighbors }}"