---
- name: Configure NE Intermediary
  hosts: eqx

  tasks:
  - name: convert config json to dict
    ansible.builtin.set_fact:
      config: "{{ config_json | from_json }}"
  - name: Configure customer side interfaces
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "{{ item.name }}"
        ipv4:
        - address: "{{ item.ip }}"
    loop: "{{ config.interfaces }}"
  - name: configure wan side for Avx edge
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "GigabitEthernet9"
        ipv4:
        - address: "{{ config.wan_ip }}"
  - name: Configure BGP globals
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{ config.customer_side_asn }}"
        bgp:
          router_id: 
            address: "{{ config.router_id }}"
          log_neighbor_changes: true
        networks:
        - address: "{{ config.wan_network }}"
          netmask: "{{ config.wan_netmask }}"
        neighbors:
        - neighbor_address: "{{ item.ip }}"
          activate: true
          remote_as: "{{ item.asn }}"
    loop: "{{ config.neighbors }}"