---
- name: Configure NE Intermediary
  hosts: all

  tasks:
  - name: Load interface and neighbor config
    ansible.builtin.include_vars:
      file: config.json
      name: config
  - name: Configure customer side interfaces
    cisco.ios.ios_l3_interfaces:
      config:
      - name: "{{ item.name }}"
        ipv4:
        - address: "{{ item.ip }}"
      - name: "GigabitEthernet9"
        ipv4:
        - address: "{{ config.wan_ip }}"
    loop: {{ config.interfaces }}
    operation: merge
  - name: Configure BGP
    cisco.ios.ios_bgp_global:
      config:
        as_number: "{{ config.customer_side_asn }}"
        router_id: 
        - address: "{{ config.wan_ip }}"
        log_neighbor_changes:
          set: true
        neighbors:
        - neighbor_address: "{{ item.ip }}"
          activate: true
          remote_as: "{{ item.asn }}"
        loop: {{ config }}
        networks:
        - address: "{{ config.wan_network }}"
      operation: merge